### ISSUE TITLE
Error on emerging app-eselect/eselect-wine-1.5::bobwya

### ISSUE THREAD

**Issue by bjl66733** [bobwya/bobwya#16]
`>>> Emerging (1 of 1) app-eselect/eselect-wine-1.5::bobwya
 * eselect-wine-1.5.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                       [ ok ]
>>> Unpacking source...
>>> Unpacking eselect-wine-1.5.tar.gz to /var/tmp/portage/app-eselect/eselect-wine-1.5/work
>>> Source unpacked in /var/tmp/portage/app-eselect/eselect-wine-1.5/work
 * ERROR: app-eselect/eselect-wine-1.5::bobwya failed (prepare phase):
 *   The source directory '/var/tmp/portage/app-eselect/eselect-wine-1.5/work/eselect-wine-1.5' doesn't exist
 * 
 * Call stack:
 *            ebuild.sh, line  767:  Called __ebuild_main 'prepare'
 *   phase-functions.sh, line 1008:  Called __dyn_prepare
 *   phase-functions.sh, line  372:  Called die
 * The specific snippet of code:
 *   		die "The source directory '${S}' doesn't exist"
 * 
 * If you need support, post the output of `emerge --info '=app-eselect/eselect-wine-1.5::bobwya'`,
 * the complete build log and the output of `emerge -pqv '=app-eselect/eselect-wine-1.5::bobwya'`.
 * The complete build log is located at '/var/tmp/portage/app-eselect/eselect-wine-1.5/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-eselect/eselect-wine-1.5/temp/environment'.
 * Working directory: '/var/tmp/portage/app-eselect/eselect-wine-1.5/homedir'
 * S: '/var/tmp/portage/app-eselect/eselect-wine-1.5/work/eselect-wine-1.5'`

**Comment by bobwya** [comment]
Ah sorry... That's because I (oops) renamed the Upstream repository - without sufficient testing of this package! So I've reverted the name and checked the package installs OK.

Should be fixed with:

 * **=app-eselect/wine-1.5-r1**

Anyway I'll leave the issue open - for you to check at your end!

**Comment by bjl66733** [comment]
`>>> Install eselect-wine-1.5-r1 into /var/tmp/portage/app-eselect/eselect-wine-1.5-r1/image/ category app-eselect
>>> Completed installing eselect-wine-1.5-r1 into /var/tmp/portage/app-eselect/eselect-wine-1.5-r1/image/

 * Final size of build directory: 96 KiB
 * Final size of installed tree: 96 KiB`

It now installs ty for the fix, in the future as currently I'm still getting to know the portage/emerge system to hopefully be able to fix the issues and help out the community.
